### ISSUE TITLE
What dose label_count mean?

### ISSUE THREAD

**Issue by mast1ren** [LoraLinH/Semi-supervised-Crowd-Counting-via-Density-Agency#4]
label_count = torch.tensor(
            [0.00016, 0.0048202634789049625, 0.01209819596260786, 0.02164922095835209, 0.03357841819524765,
             0.04810526967048645, 0.06570728123188019, 0.08683456480503082, 0.11207923293113708, 0.1422334909439087,
             0.17838051915168762, 0.22167329490184784, 0.2732916474342346, 0.33556100726127625, 0.41080838441848755,
             0.5030269622802734, 0.6174761652946472, 0.762194037437439, 0.9506691694259644, 1.2056223154067993,
             1.5706151723861694, 2.138580322265625, 3.233219861984253, 7.914860725402832]) in file regression_trainer.py, line 85.
Is it a pre-count data of the dataset used? How can I get it if I want to train another dataset?

**Comment by LoraLinH** [comment]
The setting is following UEPNet (https://github.com/TencentYoutuResearch/CrowdCounting-UEPNet)

**Comment by mast1ren** [comment]
I see. Thank u!
